### PR TITLE
📈 Add basic ga events

### PR DESCRIPTION
**Pull request by williamchong**

### CODE REVIEW

**Comment by nwingt** [comment]
Should merge this into `feature/airdrop` instead `main` first?

**Comment by williamchong** [comment]
> Should merge this into `feature/airdrop` instead `main` first?

yes, switched base branch

**Comment by williamchong** [comment]
@nwingt updated to also add events for wallet connect change

**Comment by williamchong** [comment]
@nwingt can this be merged for release?

**Pull request merged**
